Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
    class Thing(Dict):
        
        class Name(String.minLength(1)+ Type__[XSD.string]):
            "the users name. user a single to satisfy any naming except empty."
        name: Name.default("schemata").text()
        positive_integer: Integer[1:] + Type__[XSD.integer]            
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-52e5f5cbe99d>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mclass[0m [0mThing[0m[0;34m([0m[0mDict[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m     [0;32mclass[0m [0mName[0m[0;34m([0m[0mString[0m[0;34m.[0m[0mminLength[0m[0;34m([0m[0;36m1[0m[0;34m)[0m[0;34m+[0m [0mType__[0m[0;34m[[0m[0mXSD[0m[0;34m.[0m[0mstring[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m         [0;34m"the users name. user a single to satisfy any naming except empty."[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mname[0m[0;34m:[0m [0mName[0m[0;34m.[0m[0mdefault[0m[0;34m([0m[0;34m"schemata"[0m[0;34m)[0m[0;34m.[0m[0mtext[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-2-52e5f5cbe99d>[0m in [0;36mThing[0;34m()[0m
[1;32m      1[0m [0;32mclass[0m [0mThing[0m[0;34m([0m[0mDict[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m     [0;32mclass[0m [0mName[0m[0;34m([0m[0mString[0m[0;34m.[0m[0mminLength[0m[0;34m([0m[0;36m1[0m[0;34m)[0m[0;34m+[0m [0mType__[0m[0;34m[[0m[0mXSD[0m[0;34m.[0m[0mstring[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m         [0;34m"the users name. user a single to satisfy any naming except empty."[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mname[0m[0;34m:[0m [0mName[0m[0;34m.[0m[0mdefault[0m[0;34m([0m[0;34m"schemata"[0m[0;34m)[0m[0;34m.[0m[0mtext[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Type__' is not defined
NameError: name 'Type__' is not defined

